assist_pipeline:
automation: !include automations.yaml
backup:
config:
conversation:
counter:
energy:
frontend:
  themes: !include_dir_merge_named themes
hardware:
history:
homeassistant_alerts:
image_upload:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
logger:
map:
mobile_app:
my:
network:
person:
schedule:
scene: !include scenes.yaml
script: !include scripts.yaml
stream:
sun:
system_health:
tag:
timer:
webhook:
zone:
